README.md, xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAEBuffer.cpp, xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAEBuffer.h, xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAEStream.cpp, xbmc/cores/AudioEngine/Utils/AEChannelInfo.cpp
@FernetMenta @fritsch @AlwinEsch 
These commits remove AudioDSP from ActiveAEBuffer class. After this is merged I will start to PR my AudioDSP fixes.
=> Remove AudioDSP from ActiveAEBuffer

xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.h
Here was a build failure with missing include:
```
[ 87%] Building CXX object build/cores/VideoPlayer/demuxers/CMakeFiles/dvddemuxers.dir/DVDDemuxFFmpeg.cpp.o
In file included from /home/alwinus/Development/mupel/build/kodi-AlwinEsch/kodi-linux-x86_64/xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp:21:0:
/home/alwinus/Development/mupel/build/kodi-AlwinEsch/kodi-linux-x86_64/xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.h:146:17: error: ‘unique_ptr’ is not a member of ‘std’
std::map<int, std::unique_ptr<CDemuxParserFFmpeg>> m_parsers;
^~~
/home/alwinus/Development/mupel/build/kodi-AlwinEsch/kodi-linux-x86_64/xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.h:146:17: error: ‘unique_ptr’ is not a member of ‘std’
/home/alwinus/Development/mupel/build/kodi-AlwinEsch/kodi-linux-x86_64 …
```
=> VideoPlayer: Fix build

xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxFFmpeg.cpp
tested samples with fourcc tags and without.
=> VideoPlayer: drop obsolete code, patch is long in ffmpeg

xbmc/addons/ScreenSaver.cpp, xbmc/addons/ScreenSaver.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/xbmc_scr_dll.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/xbmc_scr_types.h
Remove a never used call for screensaver's
The `GetInfo(...)` is no more required on them anymore.
=> [addon] remove not needed 'GetInfo(...)' call for ScreenSaver

xbmc/cores/AudioEngine/AESinkFactory.cpp
This fix the following compiler fault with add of missing header.
```
[ 12%] Building CXX object build/cores/audioengine/CMakeFiles/audioengine.dir/AESinkFactory.cpp.o
/home/alwin/Development/kodi/agile/kodi-agile/xbmc/cores/AudioEngine/AESinkFactory.cpp: In static member function ‘static IAESink* CAESinkFactory::TrySink(std::__cxx11::string&, std::__cxx11::string&, AEAudioFormat&)’:
/home/alwin/Development/kodi/agile/kodi-agile/xbmc/cores/AudioEngine/AESinkFactory.cpp:128:18: error: expected type-specifier before ‘CAESinkPULSE’
sink = new CAESinkPULSE();
^
/home/alwin/Development/kodi/agile/kodi-agile/xbmc/cores/AudioEngine/AESinkFactory.cpp:132:18: error: expected type-specifier before ‘CAESinkALSA’
sink = new CAESinkALSA();
^
/home/alwin/Development/kodi/agile/kodi-agile/xbmc/cores/Audi …
```
=> [audioengine] fix compile fault

project/cmake/treedata/common/subdirs.txt
This fix the following linker error:
```
build/input/input.a(InputManager.cpp.o):InputManager.cpp:function CInputManager::RegisterMouseHandler[abi:cxx11](MOUSE::IMouseInputHandler*): error: undefined reference to 'MOUSE::CMouseInputHandling::CMouseInputHandling(MOUSE::IMouseInputHandler*, MOUSE::IMouseButtonMap*)'
build/input/input.a(InputManager.cpp.o):InputManager.cpp:function CInputManager::CInputManager(): error: undefined reference to 'vtable for MOUSE::CMouseWindowingButtonMap'
/usr/bin/ld.gold: the vtable symbol may be undefined because the class is missing its key function
build/input/input.a(InputManager.cpp.o):InputManager.cpp:function CInputManager::CInputManager(): error: undefined reference to 'KEYBOARD::CKeyboardEasterEgg::CKeyboardEasterEgg()' …
```
=> [cmake] fix compile with add of missing parts

xbmc/addons/kodi-addon-dev-kit/include/kodi/libKODI_peripheral.h
Was removed on rework, but now put back to prevent compile errors without
rework as long as possible on add-ons.
=> [peripheral] bring back the use of namespace ADDON to header

xbmc/addons/InputStream.cpp, xbmc/addons/PVRClient.cpp, xbmc/addons/PVRClient.h, xbmc/addons/Visualisation.cpp, xbmc/cores/AudioEngine/Engines/ActiveAE/AudioDSPAddons/ActiveAEDSPAddon.cpp, xbmc/cores/AudioEngine/Engines/ActiveAE/AudioDSPAddons/ActiveAEDSPAddon.h, xbmc/games/addons/GameClient.cpp, xbmc/games/addons/GameClient.h, xbmc/peripherals/addons/PeripheralAddon.cpp, xbmc/peripherals/addons/PeripheralAddon.h
This remove the not good usable use of `try` and `catch` on PVR add-on handling.
@FernetMenta Is the remove of them the right way? If yes becomes it also done on other add-on types.
=> [addons] remove use of try, catch

xbmc/guilib/FFmpegImage.cpp, xbmc/guilib/FFmpegImage.h
This is the first part (the more or less easy one) to the the codecpar transition.
Before: We used the stream's own codec_ctx that we opened and closed
Now: We use a member in combination with avcodec_parameters_to_context
I am not yet fully familiar with the way ffmpeg is now working. Happy for comments. It's tested and working.
=> FFmpegPicture: Transition direct access of codec to codecpar

xbmc/addons/AddonDll.h
Removes two include functions from CAddonDll who not present.
=> [addons] remove dead code on CAddonDll

xbmc/guilib/FFmpegImage.cpp, xbmc/guilib/FFmpegImage.h
This is the "easy transition" for the avcodec_encode_video2 and avcodec_decode_video2
Btw. would it make sense to add those as static method into a util class?
Also one question: I have nothing to send if I get the EAGAIN any tipp on that?
Tested and working.
Edit: Very good documentation: https://blogs.gentoo.org/lu_zero/2016/03/29/new-avcodec-api/
=> FFmpegImage: Deprecate avcodec_encode_video2 and avcodec_decode_video2

xbmc/guilib/FFmpegImage.cpp
This fixes encoding of images. With the new API the resulting AVPacket is allocated by the encoder. That means it does not use our memory anymore, see: https://ffmpeg.org/doxygen/trunk/group__lavc__decoding.html#ga5b8eff59cf259747cf0b31563e38ded6
~Do you see a way arround having to copy the memory?~
=> FFmpegPicture: Adapt to new avcodec_receive_packet behaviour

xbmc/addons/AddonDll.cpp, xbmc/addons/AddonDll.h, xbmc/addons/DllAddon.h, xbmc/addons/ScreenSaver.cpp, xbmc/addons/ScreenSaver.h, xbmc/addons/Visualisation.cpp, xbmc/addons/kodi-addon-dev-kit/include/kodi/xbmc_scr_dll.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/xbmc_scr_types.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/xbmc_vis_dll.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/xbmc_vis_types.h, xbmc/cores/VideoPlayer/DVDInputStreams/InputStreamAddon.cpp
The Stop() function was nearly never needed, also match this not the multiple instance way, further was also never a equivalent with "Start()" present.
For this reasons becomes it removed.
=> [addons] remove 'Stop()' from binary add-on interface

addons/kodi.adsp/addon.xml, addons/kodi.inputstream/addon.xml, addons/kodi.peripheral/addon.xml, addons/xbmc.pvr/addon.xml, xbmc/addons/InputStream.cpp, xbmc/addons/PVRClient.cpp, xbmc/addons/kodi-addon-dev-kit/include/kodi/kodi_adsp_dll.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/kodi_adsp_types.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/kodi_inputstream_dll.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/kodi_inputstream_types.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/kodi_peripheral_dll.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/kodi_peripheral_types.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/versions.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/xbmc_pvr_dll.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/xbmc_pvr_types.h, xbmc/cores/AudioEngine/Engines/ActiveAE/AudioDSPAddons/ActiveAEDSPAddon.cpp, xbmc/cores/AudioEngine/Engines/ActiveAE/AudioDSPAddons/ActiveAEDSPAddon.h, xbmc/peripherals/addons/PeripheralAddon.cpp
This standardize the GetCapabilities add-on functions on all add-on types where it is used to the same way.
Further is the return value where used before removed, has never seen a add-on who has returned something else as OK.
=> [addons] standardize GetCapabilities add-on functions

xbmc/addons/kodi-addon-dev-kit/include/kodi/versions.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/xbmc_addon_dll.h
This function becomes used to translate string names to related id number.
Required to identify the on add-on xml defined parts used on code.
The second commit is only the remove of no more needed part.
=> [addons] add GetTypeId function to version.h

system/shaders/convolution-6x6.glsl
I think this was broken since longer time. But as those shaders are only to be enabled via advancedsettings no one seems to have realized.
=> convolution-6x6: Fix assignemnt of vec4

xbmc/cores/AudioEngine/Engines/ActiveAE/ActiveAE.cpp
See topic. Core of DTS-HD is DTS.
=> ActiveAE: Fix dts of CORE after 731fd4de0

CMakeLists.txt, addons/kodi.guilib/addon.xml, addons/kodi.guilib/addon.xml.in, cmake/installdata/common/addons.txt, cmake/scripts/common/GenerateVersionedFiles.cmake, cmake/scripts/common/Macros.cmake, cmake/scripts/common/PrepareEnv.cmake, xbmc/addons/AddonDll.cpp, xbmc/addons/DllAddon.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/libKODI_guilib.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/versions.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/xbmc_addon_dll.h
This commits fix with one the stupid build fault on windows where `__declspec(dllexport)` can not work with a `const char*` as return.
One revert the changes for guilib addon.xml
Also becomes the version definition parts from versions.h renamed to have later equal with them used on cmake.
=> [addons] cleanup and improve changes

tools/buildsteps/win32/buildhelpers.sh
This is related to https://github.com/xbmc/xbmc/pull/10941
Want to have it for override the system build threads to have one time the windows build working without stupid reworks during compile.
=> [jenkins] allow override of cpu build threads on locally used systems

xbmc/addons/AddonDll.cpp, xbmc/addons/AddonDll.h, xbmc/addons/DllAddon.h, xbmc/addons/ScreenSaver.cpp, xbmc/addons/ScreenSaver.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/AddonBase.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/xbmc_addon_dll.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/xbmc_scr_dll.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/xbmc_scr_types.h
This request update/add the complete reworked new header `AddonBase.h` for the add-on base who was before only in `C`, now complete in `C++`.
With them becomes a lot of not needed work removed on add-on's.
For backward compatibility use it currently still the old interface functions who are set by macro `ADDONCREATOR` but on end becomes this cleaned up and all functions except ADDON_Create are done by another way.
Until final come for them improvements and cleanups.
Tested here currently only with screensavers.
=> [addons] add initial base add-on C++ support

xbmc/addons/AddonDll.cpp, xbmc/addons/AddonDll.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/AddonBase.h
This add the first callbacks over the new way to add-on header. With them
is on add-on start the table already set and something like "XBMC->RegisterMe(hdl)"
no more needed.
There comes a bigger cleanup of "AddonBase.h" after them is in.
Currently don't touch this the old way and all old style add-ons don't need a
rework.
=> [addons] add first initial new addon to kodi callbacks

xbmc/addons/AddonDll.cpp, xbmc/addons/AddonDll.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/AddonBase.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/screensaver/Screensaver.h
After last changes cleanup this the header to make it more clear.
Everything with a "/*" or "//" comment is used inside headers and not related
for add-on development itself.
=> [addons] cleanup main addon header AddonBase.h

CMakeLists.txt, addons/kodi.global.gui/addon.xml.in, addons/kodi.global.main/addon.xml.in, addons/kodi.instance.adsp/addon.xml.in, addons/kodi.instance.audiodecoder/addon.xml.in, addons/kodi.instance.audioencoder/addon.xml.in, addons/kodi.instance.game/addon.xml.in, addons/kodi.instance.inputstream/addon.xml.in, addons/kodi.instance.peripheral/addon.xml.in, addons/kodi.instance.pvr/addon.xml.in, addons/kodi.instance.screensaver/addon.xml.in, addons/kodi.instance.visualization/addon.xml.in, cmake/installdata/common/addons.txt, cmake/scripts/common/GenerateVersionedFiles.cmake, cmake/scripts/common/Macros.cmake, cmake/scripts/common/PrepareEnv.cmake, xbmc/addons/kodi-addon-dev-kit/include/kodi/libKODI_guilib.h
This changes automate the set of versions of addon.xml's inside Kodi itself. There becomes from `versions.h` the version read and added to `addon.xml.in` files.
The definitions are identical with the names inside versions.h except that to the start string a "ADDON_" is added, to prevent conflicts if the same name becomes used for something else.
By them becomes a lot of work on xml's and cmake in case of changes avoided.
Rework to have windows build working other parts are in #64
=> [cmake] automate addon.xml version set (Step 2)

cmake/treedata/common/subdirs.txt, xbmc/addons/AddonBuilder.cpp, xbmc/addons/AddonDll.cpp, xbmc/addons/CMakeLists.txt, xbmc/addons/interfaces/kodi/CMakeLists.txt, xbmc/addons/interfaces/kodi/General.cpp, xbmc/addons/interfaces/kodi/General.h, xbmc/addons/interfaces/kodi/README.md, xbmc/addons/interfaces/kodi/screensaver/CMakeLists.txt, xbmc/addons/interfaces/kodi/screensaver/Screensaver.cpp, xbmc/addons/interfaces/kodi/screensaver/Screensaver.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/AddonBase.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/General.h, xbmc/windows/GUIWindowScreensaver.h
This request add the initial part of the new used add-on library way for callbacks.
With the commit of them can be seen how a it can changed in future.
Further move the first commit the screensaver class files of Kodi to his final place.
@FernetMenta on second commit is the alternative to the old libXBMC_addon way to see :D
=> [addons] add first global add-on callback interface

xbmc/cores/RetroPlayer/RetroPlayerVideo.cpp
This fix a compile fault who was come with https://github.com/FernetMenta/kodi-agile/pull/74
```
./kodi-agile/xbmc/cores/RetroPlayer/RetroPlayerVideo.cpp: In member function ‘virtual bool GAME::CRetroPlayerVideo::OpenEncodedStream(AVCodecID)’:
./kodi-agile/xbmc/cores/RetroPlayer/RetroPlayerVideo.cpp:83:3: error: ‘CDemuxStreamVideo’ was not declared in this scope
CDemuxStreamVideo videoStream;
^
./kodi-agile/xbmc/cores/RetroPlayer/RetroPlayerVideo.cpp:86:3: error: ‘videoStream’ was not declared in this scope
videoStream.uniqueId = GAME_STREAM_VIDEO_ID;
^
./kodi-agile/xbmc/cores/RetroPlayer/RetroPlayerVideo.cpp:88:22: error: ‘STREAM_VIDEO’ was not declared in this scope
videoStream.type = STREAM_VIDEO;
^
./kodi-agile/xbmc/cores/RetroPlayer/RetroPlayerVideo.cpp:89:24: error: …
```
=> RetroPlayer: fix compile fault

xbmc/addons/interfaces/kodi/General.cpp, xbmc/addons/interfaces/kodi/General.h
Crazy windows fault, a variable as 'interface' brings stupid compile
error messages.
=> [addons] fix windows build by prevent of 'interface' as value name

xbmc/cores/VideoPlayer/DVDCodecs/Video/MMALCodec.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/MMALCodec.h, xbmc/cores/VideoPlayer/DVDCodecs/Video/MMALFFmpeg.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/MMALFFmpeg.h, xbmc/cores/omxplayer/OMXAudio.cpp, xbmc/cores/omxplayer/OMXAudioCodecOMX.cpp, xbmc/cores/omxplayer/OMXPlayerAudio.cpp
With just the ffmpeg 3.2 changes and excluding omxplayer commit all seems good on pi (I've tested on last couple of milhouse builds).
The subsequent AE changes break omxplayer, so that will need more work - I've just hacked it so it builds (but doesn't work).
One issue is I need to allocate an extra picture buffer on GPU compared to kodi master.
That only seems necessary with live TV (e.g. tvheadend), but not for similar interlaced video files.
That suggests renderer is now holding onto amn additional picture.
Is that a known change? It would be nice to avoid or at least understand that.
=> [RBP] Fix up MMAL for ffmpeg 3.2 and kodi-agile

xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodecAndroidMediaCodec.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodecAndroidMediaCodec.h
MediaCodec Audio Implementation.
From factory side the decoder is currently never taken (only if ffmpeg would fail).
If this one is merged I'll change factory to use mediacodec if cryptoinfo is available.
=> [android] MediaCodec Audio

xbmc/addons/Addon.cpp, xbmc/addons/Addon.h, xbmc/addons/AddonDll.cpp, xbmc/addons/AddonDll.h, xbmc/addons/GUIDialogAddonSettings.cpp, xbmc/addons/IAddon.h, xbmc/addons/interfaces/kodi/General.cpp, xbmc/addons/interfaces/kodi/General.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/AddonBase.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/General.h
Included changes makes the access of values on "SetSetting(...)" call
a bit easier to access.
Further is the settings set improved but due to duplicate use of CAddon Classes
currently not direct usable.
=> [addons] improve add-on interface settings handling

cmake/treedata/common/subdirs.txt, xbmc/addons/AddonDll.cpp, xbmc/addons/interfaces/kodi/General.cpp, xbmc/addons/interfaces/kodi/General.h, xbmc/addons/interfaces/kodi/gui/CMakeLists.txt, xbmc/addons/interfaces/kodi/gui/DialogOK.cpp, xbmc/addons/interfaces/kodi/gui/DialogOK.h, xbmc/addons/interfaces/kodi/gui/General.cpp, xbmc/addons/interfaces/kodi/gui/General.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/AddonBase.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/General.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/gui/DialogOK.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/gui/General.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/gui/definitions.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/screensaver/Screensaver.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/visualization/Visualization.h
This does the next cleanup of new add-on headers and bring in the initial new gui interface (currently only with OK Dialog and standard function).
Currently still using screensavers and visualizations to test new interface ways, on add-on side it works very nice.
Also makes itself really proven to use a namespace with the developer software. There comes with them a very easy auto update and select of functions and parts :D
=> [addons] rework steps

xbmc/addons/InputStream.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/kodi_inputstream_types.h
Having inputstream.capabilities as a set of bools has following disadvantages:
- Memory footprint
- processing performance
- each new capability forces an api change because of changed struct size
- resetting the mask is much easier than setting all elements to "false"
This list of bools is something wich hount me for long time, at least every time I strumble over it.
This PR gives me some minutes of sleep back :-)
=> Change InputStreamCaps from multibool to bitmask

xbmc/cores/VideoPlayer/DVDCodecs/Video/MMALCodec.cpp
Found the real reason for needing an extra decoded picture.
We now call GetPicture more than AddData, so we are not calling Prime
(which releases unreferenced pictures back to MMAL) enough.
Adding the extra Prime call means the extra picture is not required.
=> [MMAL] Fixes for stalled video

xbmc/cores/VideoPlayer/DVDFileInfo.cpp
Thumbnail extraction from video files doesn't currently work.
Need to use result of GetPicture not AddData to check for a picture.
=> DVDFileInfo: Fix video thumbnail extraction

xbmc/addons/kodi-addon-dev-kit/include/kodi/kodi_inputstream_types.h
see title.
enum values forbid making bit combinations as they are thougt to be a unique value.
This PR makes mask building lot easier.
=> change type od cap mask to avoid errors when building masks

xbmc/cores/VideoPlayer/DVDCodecs/Video/VAAPI.cpp
After discussion with Christian, we should not rely on driver magic: https://cgit.freedesktop.org/vaapi/intel-driver/tree/src/i965_drv_video.c#n1338
=> VAAPI: Properly set VA_FOURCC_P010 for the attribute

xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodec.h, xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.h, xbmc/cores/VideoPlayer/DVDCodecs/Video/DXVA.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/DXVA.h, xbmc/cores/VideoPlayer/DVDCodecs/Video/MMALCodec.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/MMALCodec.h, xbmc/cores/VideoPlayer/DVDCodecs/Video/MMALFFmpeg.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/MMALFFmpeg.h, xbmc/cores/VideoPlayer/DVDCodecs/Video/VAAPI.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/VAAPI.h, xbmc/cores/VideoPlayer/DVDCodecs/Video/VDPAU.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/VDPAU.h, xbmc/cores/VideoPlayer/DVDCodecs/Video/VTB.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/VTB.h, xbmc/cores/VideoPlayer/DVDFileInfo.cpp, xbmc/cores/VideoPlayer/DVDMessageQueue.cpp, xbmc/cores/VideoPlayer/DVDMessageQueue.h, xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp
cleanup interface for video decoder
this should make clear that:
- the old way of combining flags is history
- videoplayer calls GetPicture on every cycle
- GetPicture controls the process
- decoder has to consume the entire demux packet
@peak3d @popcornmix ping
=> VideoPlayer: cleanup videoCodec interface

xbmc/addons/AddonInfo.cpp
After the change to new system was Kodi's "special://" used, with them
comes a problem to locate present installed libraries e.g on
'/usr/local/lib/kodi/addons/*'.
This translate the path on creation of CAddonInfo and prevent the
problems on add-on load.
=> [addons] fix installed add-on location search

xbmc/addons/AddonInfo.h, xbmc/addons/AddonManager.cpp, xbmc/addons/AddonManager.h, xbmc/guilib/GUIVisualisationControl.cpp, xbmc/guilib/GUIVisualisationControl.h, xbmc/windows/GUIWindowScreensaver.cpp, xbmc/windows/GUIWindowScreensaver.h
This add the support to handle multiple instances together on one
add-on.
A addon class stays so long created as it is used by instances,
after the last instance release it becomes the addon class destroyed.
Further stays the data on CAddonDll and if them call for a type an
"CreateInstance" on add-on becomes also the first time a "Create"
performed, every other "CreateInstance" call do know that the
"Create" is already done and becomes skipped.
=> [addons] add multiple instance support to Kodi

xbmc/addons/AddonDll.cpp, xbmc/addons/AddonDll.h, xbmc/addons/DllAddon.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/AddonBase.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/versions.h
This add a parent instance pointer to the addon CreateInstance call.
If a parent pointer is set becomes the CreateInstance of them called,
otherwise them from base.
=> [addons] add support to create child instance from parent

xbmc/addons/AddonDll.cpp, xbmc/addons/AddonDll.h, xbmc/addons/AddonInfo.h, xbmc/addons/AddonManager.cpp, xbmc/addons/AddonManager.h, xbmc/addons/AudioEncoder.cpp, xbmc/addons/AudioEncoder.h, xbmc/cores/AudioEngine/Engines/ActiveAE/AudioDSPAddons/ActiveAEDSP.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/AddonVideoCodec.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/AddonVideoCodec.h, xbmc/cores/VideoPlayer/DVDInputStreams/InputStreamAddon.cpp, xbmc/cores/VideoPlayer/DVDInputStreams/InputStreamAddon.h
With this change becomes the standard parts done on the parent
class IAddonInstanceHandler.
About screensaver and visualization is it not possible to use
this parts and need to find a better way to prevent problems if the
same way becomes used somewhere else.
=> [addons] reduce amount of parts on add-on instance classes

xbmc/addons/Addon.cpp
With the complete map copy was before the values from hidden
parts removed.
=> [addons] fix save if hidden settings are present

xbmc/addons/AddonDatabase.cpp, xbmc/addons/AddonDatabase.h, xbmc/addons/AddonManager.cpp
Currently new installed addons disappear after kodi restart.
Reason is, that they have not been inserted into the installed table from addon27.db.
This PR fixes this issue
=> insert new addons into installed table

xbmc/addons/AddonInstaller.cpp, xbmc/cores/VideoPlayer/DVDCodecs/DVDFactoryCodec.cpp, xbmc/utils/URIUtils.cpp
1.) Dont try to use other decoder if external decoder is given but fails.
2.) Remove  addon's zip file from packages cache folder in case InstalFromZip is called.
Currently the file from packages cache is choosen with higher priority than the zip file selected.
This makes it really hard during a developing process.
=> Videocodec / ready to merge :-)

xbmc/filesystem/CurlFile.cpp
For further discussion.
There are some custom headers wich have to be passed to the content provider during the license request.
Currently in CCurlFile there is a filter wich eliminates all unknown Header pairs.
To force kodi to use them they have to be prefixed with [F] (F = Force).
=> CURLFile: Remove filter for unknown HTTP header / control log visibility of header values 

xbmc/windows/GUIMediaWindow.cpp
The addon rework changed the initial path logic that &content_type=[type] is always added, regardless if there is only one provides defined in addon.xml.
This leads to double entry in history and needs 2 [back] clicks to leave the addon.
This PR skips the additional history entry and behaviour is now again as before.
Benefit: this fixes also the bug in master if more than 1 provides is defined.
=> ignore content_type option in plugin::history

xbmc/Application.cpp
When playing a playlist with several files and a vidoe finishes,
KODI switches to the next video in playlist. That action causes
fulscreen window being deinited and previous one displayed instead
(which breaks playlist playback in different ways depending on
what previous window were displayed before playlist playback has
been started).
Fixes regression introduced by:
commit acd30c1bf3 Implement FullscreenGame window
Author: Garrett Brown <themagnificentmrb@gmail.com>
=> don't go back to previous window when playing playlist

xbmc/cores/ExternalPlayer/ExternalPlayer.cpp, xbmc/windowing/X11/WinSystemX11GLContext.cpp
These "fixes" are required for my setup and may be needed by other users.
First one removes the double quotes enclosing the executable name in ExternalPlayer, which breaks it on my Ubuntu 17.10 system. These double-quotes are only required around the filename arg.
Second one allows 10bits/channel visual detection as a fallback if 8bits/channel is not found (and prevents the associated kodi crash), which may be needed eventually when higher bit-depths will become better supported on linux.
=> [linux] Fixes for linux builds
