FernetMenta/kodi-agile

xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodec.h, xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodecFFmpeg.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodecFFmpeg.h, xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodecPassthrough.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodecPassthrough.h, xbmc/cores/VideoPlayer/VideoPlayerAudio.cpp, xbmc/cores/paplayer/VideoPlayerCodec.cpp, xbmc/cores/paplayer/VideoPlayerCodec.h
=> VideoPlayer: adapt audio to ffmpeg 3.2

xbmc/cores/ExternalPlayer/ExternalPlayer.cpp, xbmc/cores/VideoPlayer/VideoPlayerAudio.cpp, xbmc/cores/paplayer/PAPlayer.cpp
=> [Windows] Fix Visual Studio warnings (we have quite a lot of them)

xbmc/addons/AddonDll.cpp
Sorry, was a stupid fault before from me
=> [addons] fix fault of failed addon load

xbmc/cores/VideoPlayer/DVDCodecs/Video/VAAPI.cpp
Just a minor, nothing fancy at all.
Btw. what about the rendering part? I don't see from the code how we manage the 10 bit surfaces in our render. Is there no chance needed?
=> VAAPI: Fix log message

ADDON_NOTES.md
This is my info doc about the repositories used for kodi agile.
=> add ADDON_NOTES.md to inform about add-on changes

cmake/scripts/linux/Install.cmake
Commits self explaining - at least I hope so.
=> kodi-addon-dev-kit: Fix make install and dependencies

xbmc/addons/ScreenSaver.cpp
This cleanup the screensaver class to match standard, remove possible memleaks and reduce amount of process work.
=> [screensaver] update after upstream merge

cmake/scripts/linux/Install.cmake, xbmc/addons/ScreenSaver.cpp, xbmc/addons/ScreenSaver.h, xbmc/addons/addon-bindings.mk, xbmc/addons/kodi-addon-dev-kit/include/kodi/AddonBase.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/kodi_adsp_types.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/kodi_audiodec_types.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/kodi_audioengine_types.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/kodi_game_types.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/kodi_inputstream_types.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/kodi_peripheral_types.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/xbmc_addon_types.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/xbmc_audioenc_types.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/xbmc_pvr_types.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/xbmc_scr_types.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/xbmc_vis_types.h
In this changes becomes the new main add-on header 'AddonBase.h' added. Also is the screensaver header reworked to coming table structure and on last commit becomes the new header added to all types to have on next changes the needed defines.
There is a lot to do before it becomes final, for this look this and some other coming a bit bad.
=> [addons] start to bring in new parts

xbmc/addons/InputStream.cpp, xbmc/addons/kodi-addon-dev-kit/include/kodi/kodi_inputstream_types.h, xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemux.h, xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxPacket.h, xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxUtils.cpp, xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxUtils.h, xbmc/cores/VideoPlayer/DVDDemuxers/DemuxCrypto.h
See title...
Next steps: 
- PR mediacodec wich needs this feature (android)
- Develop dekoder in kodi wich decodes encrypted media using widevine implementation in inputstream. (all platforms != android)
=> enable transfer of encrypted stream infos from inputstream to kodi

xbmc/addons/interfaces/kodi/CMakeLists.txt, xbmc/addons/interfaces/kodi/Filesystem.cpp, xbmc/addons/interfaces/kodi/Filesystem.h, xbmc/addons/interfaces/kodi/General.cpp, xbmc/addons/kodi-addon-dev-kit/include/kodi/Filesystem.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/General.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/definitions.h
This change add the support to handle files and directories on addon with callbacks
to Kodi.
=> [addons] add new addon filesystem callback interface

xbmc/addons/Addon.h, xbmc/addons/AddonInstaller.cpp, xbmc/addons/AddonProperties.cpp, xbmc/addons/AddonProperties.h, xbmc/addons/CMakeLists.txt, xbmc/addons/Repository.cpp, xbmc/addons/Repository.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/AddonBase.h
With them become more easy to review the part.
Further makes this it better on rework.
Is taken from another request #90, this here are more easy :)
=> [addons] move AddonProps part to new files

xbmc/cores/RetroPlayer/RetroPlayerAudio.cpp, xbmc/cores/VideoPlayer/DVDCodecs/DVDFactoryCodec.cpp, xbmc/cores/VideoPlayer/DVDCodecs/DVDFactoryCodec.h, xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodec.h, xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.h, xbmc/cores/VideoPlayer/DVDCodecs/Video/VTB.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/VTB.h, xbmc/cores/VideoPlayer/DVDResource.h, xbmc/cores/paplayer/VideoPlayerCodec.cpp
Reverts FernetMenta/kodi-agile#84
=> Revert "VideoPlayer: rework codec factory"

xbmc/cores/RetroPlayer/RetroPlayerAudio.cpp, xbmc/cores/VideoPlayer/DVDCodecs/DVDFactoryCodec.cpp, xbmc/cores/VideoPlayer/DVDCodecs/DVDFactoryCodec.h, xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodec.h, xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.h, xbmc/cores/VideoPlayer/DVDCodecs/Video/VTB.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/VTB.h, xbmc/cores/VideoPlayer/DVDResource.h, xbmc/cores/paplayer/VideoPlayerCodec.cpp
=> VideoPlayer: rework codec factory

xbmc/cores/RetroPlayer/RetroPlayerAudio.cpp, xbmc/cores/VideoPlayer/CMakeLists.txt, xbmc/cores/VideoPlayer/DVDClock.h, xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodec.h, xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodecFFmpeg.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodecFFmpeg.h, xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodecPassthrough.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodecPassthrough.h, xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodec.h, xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecFFmpeg.h, xbmc/cores/VideoPlayer/DVDCodecs/Video/MMALCodec.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/MMALCodec.h, xbmc/cores/VideoPlayer/DVDConstants.h, xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxPacket.h, xbmc/cores/VideoPlayer/DVDFileInfo.cpp, xbmc/cores/VideoPlayer/VideoPlayerAudio.cpp, xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp, xbmc/cores/paplayer/VideoPlayerCodec.cpp
see title. only fixed the places I found, most likely I missed something....
=> call AddData with DemuxPacket

xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.h, xbmc/cores/VideoPlayer/DVDStreamInfo.cpp, xbmc/cores/VideoPlayer/DVDStreamInfo.h, xbmc/platform/android/activity/XBMCApp.cpp
MediaCodec / MediaCrypto implementation / adaption
-> include HDMI_AUDIO_PLUG action
=> Mediacrypto

xbmc/cores/VideoPlayer/DVDCodecs/DVDFactoryCodec.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.h, xbmc/platform/android/jni/MediaCrypto.cpp
=> finalize mediacodec video decoder / enable in factory

cmake/scripts/linux/Install.cmake, xbmc/addons/addon-bindings.mk, xbmc/addons/interfaces/InputStream/AddonCallbacksInputStream.cpp, xbmc/addons/interfaces/InputStream/AddonCallbacksInputStream.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/libKODI_inputstream.h
=> provide DemuxCrypto to adddon build system

xbmc/addons/kodi-addon-dev-kit/include/kodi/kodi_inputstream_types.h
sry, should be the last one regarding crypto passing for the next time
=> Remove pointer in inputstream_info

xbmc/cores/VideoPlayer/DVDCodecs/Audio/CMakeLists.txt, xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodecAndroidMediaCodec.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodecAndroidMediaCodec.h, xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.h, xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxClient.cpp
- new video decoder api
- audio cleanup
- one more forgotten place in addon -> core pipeline for cryptoSession
=> Mediaaudio

xbmc/cores/VideoPlayer/VideoPlayerVideo.cpp
=> aquire refcount for dvdmessage

xbmc/addons/AddonInfo.cpp
Reverts FernetMenta/kodi-agile#121
=> Revert "[addons] fix installed add-on location search"

xbmc/addons/Addon.h, xbmc/addons/AddonDll.cpp, xbmc/addons/AddonDll.h, xbmc/addons/AddonInfo.cpp, xbmc/addons/AddonInfo.h, xbmc/addons/ContextMenus.cpp, xbmc/addons/DllAddon.h, xbmc/addons/GUIDialogAddonInfo.cpp, xbmc/addons/GUIDialogAddonSettings.cpp, xbmc/addons/kodi-addon-dev-kit/include/kodi/AddonBase.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/xbmc_addon_cpp_dll.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/xbmc_addon_dll.h, xbmc/cores/AudioEngine/Engines/ActiveAE/AudioDSPAddons/ActiveAEDSP.cpp
Reverts FernetMenta/kodi-agile#120
=> Revert "[addons] remove never used interface functions"

xbmc/addons/AddonInfo.h
Reverts FernetMenta/kodi-agile#119
=> Revert "[addons] Fix android compile fault"

xbmc/guilib/FFmpegImage.cpp
=> FFmpegImage: Tear down ioctx correctly

xbmc/guilib/FFmpegImage.cpp
=> FFmpegImage: Add FF_INPUT_BUFFER_PADDING_SIZE to allocation

xbmc/utils/BitstreamConverter.cpp, xbmc/utils/BitstreamConverter.h
Check for h.264 recovery point as well as for IDR Frame
=> bitstream decode-start change

xbmc/cores/VideoPlayer/DVDCodecs/Video/VAAPI.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/VAAPI.h, xbmc/settings/AdvancedSettings.cpp, xbmc/settings/AdvancedSettings.h, xbmc/windowing/X11/WinSystemX11GLContext.cpp
see title
don't rely on assumptions but on facts.
=> X11: check vaapi caps on startup

xbmc/addons/AddonProvider.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/StreamCodec.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/addon-instance/Inputstream.h, xbmc/addons/kodi-addon-dev-kit/include/kodi/addon-instance/VideoCodec.h, xbmc/cores/VideoPlayer/DVDCodecs/DVDFactoryCodec.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/AddonVideoCodec.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/AddonVideoCodec.h, xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemux.h, xbmc/cores/VideoPlayer/DVDDemuxers/DVDDemuxClient.cpp, xbmc/cores/VideoPlayer/DVDInputStreams/InputStreamAddon.cpp, xbmc/cores/VideoPlayer/DVDInputStreams/InputStreamAddon.h, xbmc/cores/VideoPlayer/DVDStreamInfo.h, xbmc/cores/VideoPlayer/Process/ProcessInfo.cpp, xbmc/cores/VideoPlayer/Process/ProcessInfo.h
This is the first working set for VideoCodecAddon:
- Implemented more data passing
- Separated Addon::CodecProfiles into a separate file so it can be shared
- Added codecProfile to INPUTSTREAM_INFO
=> finalized first working step AddonVideoCodec

xbmc/addons/kodi-addon-dev-kit/include/kodi/addon-instance/VideoCodec.h, xbmc/cores/VideoPlayer/DVDCodecs/Video/AddonVideoCodec.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/AddonVideoCodec.h
VideoDecoder Addon is now capable to request decode target buffers by this new callback
=> Add AddonToKodi GetFrameBuffer

xbmc/cores/VideoPlayer/DVDCodecs/DVDFactoryCodec.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/AMLCodec.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/AMLCodec.h, xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAmlogic.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAmlogic.h
=> get amlogic decoder working

xbmc/addons/kodi-addon-dev-kit/include/kodi/addon-instance/VideoCodec.h, xbmc/cores/VideoPlayer/DVDCodecs/Video/AddonVideoCodec.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/AddonVideoCodec.h
Buffer pool Implementation for s/w decoding using AddonVideoCodec
=> Bufferpool implementation

xbmc/cores/RetroPlayer/RetroPlayerAudio.cpp, xbmc/cores/VideoPlayer/AudioSinkAE.cpp, xbmc/cores/VideoPlayer/AudioSinkAE.h, xbmc/cores/VideoPlayer/CMakeLists.txt, xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodecPassthrough.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodecPassthrough.h, xbmc/cores/VideoPlayer/DVDCodecs/DVDCodecs.h, xbmc/cores/VideoPlayer/DVDCodecs/DVDFactoryCodec.cpp, xbmc/cores/VideoPlayer/DVDCodecs/DVDFactoryCodec.h, xbmc/cores/VideoPlayer/VideoPlayerAudio.cpp, xbmc/cores/VideoPlayer/VideoPlayerAudio.h, xbmc/cores/paplayer/VideoPlayerCodec.cpp, xbmc/cores/paplayer/VideoPlayerCodec.h
another step on the road to transcoding. make VP audio able to render into an encoder instead of AE
=> VideoPlayer: create audio sink, cut dependency from audio codecs to ae'

xbmc/addons/kodi-addon-dev-kit/include/kodi/addon-instance/VideoCodec.h, xbmc/cores/VideoPlayer/DVDCodecs/Video/AddonVideoCodec.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/AddonVideoCodec.h
=> Drain / VC_EOF implementation

xbmc/addons/interfaces/kodi/addon-instance/Screensaver.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/AddonVideoCodec.cpp
=> Videocodec / Drain on Reset. Compile fix DXVA

xbmc/addons/AddonInfo.h, xbmc/addons/AddonInstaller.cpp, xbmc/cores/VideoPlayer/DVDInputStreams/InputStreamAddon.cpp
=> Videocodec

xbmc/cores/VideoPlayer/DVDInputStreams/InputStreamAddon.cpp
=> InputStreamAddon: Activate Subtitles

xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAmlogic.cpp, xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/RendererAML.cpp, xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/RendererAML.h, xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGLES.cpp, xbmc/cores/VideoPlayer/VideoRenderers/LinuxRendererGLES.h, xbmc/cores/VideoPlayer/VideoRenderers/VideoShaders/YUV2RGBShader.cpp
[AML] fix compile issues after VideoPicture cleanup
=> aml / linuxgles adaption

tools/depends/target/libandroidjni/Makefile, xbmc/cores/VideoPlayer/DVDCodecs/Audio/DVDAudioCodecAndroidMediaCodec.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp, xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/RendererMediaCodec.cpp, xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/RendererMediaCodecSurface.cpp
=> [Android]: VideoPicture::hwPic

tools/depends/target/libandroidjni/Makefile
=> [jni] interface bump

xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAmlogic.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.cpp, xbmc/cores/VideoPlayer/DVDCodecs/Video/DVDVideoCodecAndroidMediaCodec.h, xbmc/cores/VideoPlayer/VideoRenderers/HwDecRender/RendererMediaCodecSurface.cpp, xbmc/utils/BitstreamConverter.cpp, xbmc/utils/BitstreamConverter.h
And some minor simplification for AML.....
=> [Android] mpeg2 add BitstreamConverter
